In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### BOW concept (bags of words)

In [52]:
from sklearn.feature_extraction.text import CountVectorizer

In [53]:
obj = CountVectorizer()

In [54]:
X_text = [
    'I love this product',
    'This product is amazing',
    'Very bad product',
    'I hate this product'
]

In [55]:
X = obj.fit_transform(X_text)

In [56]:
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 13 stored elements and shape (4, 8)>

In [57]:
X.toarray()

array([[0, 0, 0, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 0]])

In [58]:
obj.get_feature_names_out()

array(['amazing', 'bad', 'hate', 'is', 'love', 'product', 'this', 'very'],
      dtype=object)

##### research on TF-IDF

In [59]:
y = ['Positive','Positive','Negative','Negative']

In [60]:
from sklearn.linear_model import LogisticRegression

In [61]:
model = LogisticRegression()

In [62]:
model.fit(X,y)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default sol

In [63]:
new_text = ['Amazing product']
next_text = obj.transform(new_text)

In [64]:
model.predict(next_text)

array(['Positive'], dtype='<U8')

#### TF-IDF

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [66]:
data = {
    'text': [
        'I love machine learning',
        'Machine learning is very interesting',
        'I love Python programming',
        'Python is useful for machine learning'
    ]
}

In [67]:
df = pd.DataFrame(data)

In [68]:
df

,text
0,I love machine learning
1,Machine learning is very interesting
2,I love Python programming
3,Python is useful for machine learning


In [69]:
tfidf = TfidfVectorizer()

In [70]:
X = tfidf.fit_transform(df['text'])

In [71]:
tfidf.vocabulary_

{'love': 4,
 'machine': 5,
 'learning': 3,
 'is': 2,
 'very': 9,
 'interesting': 1,
 'python': 7,
 'programming': 6,
 'useful': 8,
 'for': 0}

In [72]:
X.toarray()

array([[0.        , 0.        , 0.        , 0.53256952, 0.65782931,
        0.53256952, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.53944516, 0.42530476, 0.34432086, 0.        ,
        0.34432086, 0.        , 0.        , 0.        , 0.53944516],
       [0.        , 0.        , 0.        , 0.        , 0.52640543,
        0.        , 0.66767854, 0.52640543, 0.        , 0.        ],
       [0.49641358, 0.        , 0.39137817, 0.31685436, 0.        ,
        0.31685436, 0.        , 0.39137817, 0.49641358, 0.        ]])

In [73]:
feature_names = tfidf.get_feature_names_out()

In [74]:
feature_names

array(['for', 'interesting', 'is', 'learning', 'love', 'machine',
       'programming', 'python', 'useful', 'very'], dtype=object)

In [75]:
tfidf_df = pd.DataFrame(
    X.toarray(),
    columns=feature_names
)

In [76]:
tfidf_df

,for,interesting,is,learning,love,machine,programming,python,useful,very
0,0.000000,0.000000,0.000000,0.532570,0.657829,0.532570,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.539445,0.425305,0.344321,0.000000,0.344321,0.000000,0.000000,0.000000,0.539445
2,0.000000,0.000000,0.000000,0.000000,0.526405,0.000000,0.667679,0.526405,0.000000,0.000000
3,0.496414,0.000000,0.391378,0.316854,0.000000,0.316854,0.000000,0.391378,0.496414,0.000000


#### Gaussian NB(Naive Bayes)

In [77]:
data = pd.read_csv("C:/Users/ASUS/Desktop/FBS/Data science/Dataset/Heart.csv")

In [78]:
data.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No


In [79]:
data.describe()

,Unnamed: 0,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,299.000000
mean,152.000000,54.438944,0.679868,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.672241
std,87.612784,9.038662,0.467299,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,0.937438
min,1.000000,29.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,76.500000,48.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000
50%,152.000000,56.000000,1.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,227.500000,61.000000,1.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000
max,303.000000,77.000000,1.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000


In [80]:
data.columns

Index(['Unnamed: 0', 'Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs',
       'RestECG', 'MaxHR', 'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'AHD'],
      dtype='str')

In [81]:
data.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [82]:
data = pd.get_dummies(data, columns=['ChestPain', 'Thal'], drop_first=True, dtype=int)

In [83]:
data['AHD'] = data['AHD'].map({'No': 0, 'Yes': 1})

In [84]:
data = data.fillna(data.median(numeric_only=True))

In [85]:
X = data.drop('AHD', axis=1)
y = data['AHD']

In [86]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix

In [87]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=10)

In [88]:
gnb = GaussianNB()

In [89]:
gnb.fit(X_train, y_train)

,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)number of training samples observed in each class.","ndarray[float64](2,)","[133.,109.]"
"class_prior_ class_prior_: ndarray of shape (n_classes,)probability of each class.","ndarray[float64](2,)","[0.55,0.45]"
"classes_ classes_: ndarray of shape (n_classes,)class labels known to the classifier.","ndarray[int64](2,)","[0,1]"
epsilon_ epsilon_: floatabsolute additive value to variances.,float64,7.67e-06
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](17,)","['Unnamed: 0','Age','Sex',...,'ChestPain_typical','Thal_normal', 'Thal_reversable']"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,17
"theta_ theta_: ndarray of shape (n_classes, n_features)mean of each feature per class.","ndarray[float64](2, 17)","[[143.5 , 52.47, 0.55,..., 0.11, 0.8 , 0.17], [153.94, 56.61, 0.83,..., 0.06, 0.27, 0.64]]"
"var_ var_: ndarray of shape (n_classes, n_features)Variance of each feature per class... versionadded:: 1.0","ndarray[float64](2, 17)","[[7346.2 , 91.21, 0.25,..., 0.09, 0.16, 0.14], [8005.23, 64.9 , 0.14,..., 0.06, 0.2 , 0.23]]"


In [90]:
y_pred = gnb.predict(X_test)

In [91]:
accuracy_score(y_test, y_pred)

0.819672131147541

In [92]:
confusion_matrix(y_test, y_pred)

array([[25,  6],
       [ 5, 25]])