In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(10,20,(3,3))
arr1

array([[16, 19, 11],
       [11, 11, 19],
       [17, 18, 14]], dtype=int32)

In [3]:
arr2 = np.random.randint(20,30,(4,3))
arr2

array([[26, 26, 28],
       [24, 25, 20],
       [21, 26, 21],
       [21, 23, 25]], dtype=int32)

In [4]:
np.concatenate((arr1,arr2))

array([[16, 19, 11],
       [11, 11, 19],
       [17, 18, 14],
       [26, 26, 28],
       [24, 25, 20],
       [21, 26, 21],
       [21, 23, 25]], dtype=int32)

In [6]:
arr3 = np.random.randint(30,40,(3,4))
arr3

array([[36, 33, 35, 33],
       [31, 39, 37, 34],
       [30, 38, 31, 34]], dtype=int32)

In [ ]:
np.concatente((arr1,arr3)) # raise error

In [10]:
arr1 ,arr3

(array([[16, 19, 11],
        [11, 11, 19],
        [17, 18, 14]], dtype=int32),
 array([[36, 33, 35, 33],
        [31, 39, 37, 34],
        [30, 38, 31, 34]], dtype=int32))

In [11]:
np.concatenate((arr1,arr3),axis = 1)

array([[16, 19, 11, 36, 33, 35, 33],
       [11, 11, 19, 31, 39, 37, 34],
       [17, 18, 14, 30, 38, 31, 34]], dtype=int32)

In [12]:
np.hstack((arr1,arr3))

array([[16, 19, 11, 36, 33, 35, 33],
       [11, 11, 19, 31, 39, 37, 34],
       [17, 18, 14, 30, 38, 31, 34]], dtype=int32)

In [13]:
np.vstack((arr1,arr2))

array([[16, 19, 11],
       [11, 11, 19],
       [17, 18, 14],
       [26, 26, 28],
       [24, 25, 20],
       [21, 26, 21],
       [21, 23, 25]], dtype=int32)

In [14]:
np.split(arr3,3)

[array([[36, 33, 35, 33]], dtype=int32),
 array([[31, 39, 37, 34]], dtype=int32),
 array([[30, 38, 31, 34]], dtype=int32)]

In [15]:
np.split(arr3,2,axis = 1)

[array([[36, 33],
        [31, 39],
        [30, 38]], dtype=int32),
 array([[35, 33],
        [37, 34],
        [31, 34]], dtype=int32)]