In [5]:
import numpy as np

In [6]:
arr = np.random.randint(35,100,100)
arr

array([73, 73, 63, 99, 55, 98, 80, 40, 99, 56, 35, 46, 41, 94, 70, 68, 89,
       51, 96, 87, 89, 62, 77, 59, 52, 78, 87, 79, 45, 71, 71, 63, 58, 39,
       44, 65, 36, 45, 86, 90, 71, 96, 49, 87, 94, 65, 59, 73, 90, 54, 48,
       79, 72, 75, 84, 84, 43, 74, 47, 81, 53, 86, 35, 82, 68, 67, 65, 53,
       73, 39, 96, 39, 62, 79, 89, 37, 55, 48, 55, 70, 44, 93, 88, 36, 62,
       99, 64, 98, 80, 92, 59, 59, 86, 57, 74, 82, 73, 98, 55, 62],
      dtype=int32)

In [7]:
np.where(arr>50,True,False)

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False, False,  True,
       False, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True, False,  True, False,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
np.where(arr>50)

(array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 35, 38, 39, 40, 41, 43,
        44, 45, 46, 47, 48, 49, 51, 52, 53, 54, 55, 57, 59, 60, 61, 63, 64,
        65, 66, 67, 68, 70, 72, 73, 74, 76, 78, 79, 81, 82, 84, 85, 86, 87,
        88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),)

In [9]:
arr

array([73, 73, 63, 99, 55, 98, 80, 40, 99, 56, 35, 46, 41, 94, 70, 68, 89,
       51, 96, 87, 89, 62, 77, 59, 52, 78, 87, 79, 45, 71, 71, 63, 58, 39,
       44, 65, 36, 45, 86, 90, 71, 96, 49, 87, 94, 65, 59, 73, 90, 54, 48,
       79, 72, 75, 84, 84, 43, 74, 47, 81, 53, 86, 35, 82, 68, 67, 65, 53,
       73, 39, 96, 39, 62, 79, 89, 37, 55, 48, 55, 70, 44, 93, 88, 36, 62,
       99, 64, 98, 80, 92, 59, 59, 86, 57, 74, 82, 73, 98, 55, 62],
      dtype=int32)

In [10]:
arr = arr[arr>50]

In [11]:
arr

array([73, 73, 63, 99, 55, 98, 80, 99, 56, 94, 70, 68, 89, 51, 96, 87, 89,
       62, 77, 59, 52, 78, 87, 79, 71, 71, 63, 58, 65, 86, 90, 71, 96, 87,
       94, 65, 59, 73, 90, 54, 79, 72, 75, 84, 84, 74, 81, 53, 86, 82, 68,
       67, 65, 53, 73, 96, 62, 79, 89, 55, 55, 70, 93, 88, 62, 99, 64, 98,
       80, 92, 59, 59, 86, 57, 74, 82, 73, 98, 55, 62], dtype=int32)