In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr1 = np.array([10,3.14])
arr1

array([10.  ,  3.14])

In [5]:
arr2 = np.array([10,3.14,'a'])
arr2

array(['10', '3.14', 'a'], dtype='<U32')

In [12]:
arr

array([10, 20, 30, 40])

In [10]:
arr.shape

(4,)

In [8]:
arr.ndim

1

In [ ]:
arr.size

In [13]:
arr2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
arr2.ndim

2

In [21]:
arr2 = np.arange(1,13).reshape((3,4))
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr2[0,1],arr[1,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [25]:
arr3 = np.arange(1,25).reshape((2,4,3))
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [26]:
arr3[0,2,0]

np.int64(7)

In [27]:
arr3[0,3,0],arr3[0,1,1],arr3[1,2,2],arr3[1,3,0]

(np.int64(10), np.int64(5), np.int64(21), np.int64(22))

slicing and range is same

In [28]:
arr4 = np.arange(1,31).reshape((6,5))
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [29]:
arr4[1:5]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
arr4[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [31]:
arr4[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [32]:
arr4[1:5,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

3 Dimension array / slicing
mysql-connector-python liabrary install