In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,10).reshape((3,3))
arr2 = np.arange(2,11).reshape((3,3))
arr1,arr2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]]))

In [3]:
np.add(arr1,arr2)

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [4]:
arr1 + arr2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [5]:
np.subtract(arr2,arr1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [6]:
arr2 - arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [7]:
np.multiply(arr1,arr2)

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72, 90]])

In [8]:
arr1 * arr2

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72, 90]])

In [9]:
np.divide(arr1,arr2)

array([[0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.85714286],
       [0.875     , 0.88888889, 0.9       ]])

In [10]:
arr1 / arr2

array([[0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.85714286],
       [0.875     , 0.88888889, 0.9       ]])

In [11]:
np.dot(arr1,arr2)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [16]:
arr1 @ arr2

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [12]:
np.max(arr2)

np.int64(10)

In [17]:
np.max(arr2,axis = 1)

array([ 4,  7, 10])

In [13]:
np.argmax(arr2)

np.int64(8)

In [14]:
np.min(arr2)

np.int64(2)

In [18]:
np.min(arr2,axis = 1)

array([2, 5, 8])

In [15]:
np.argmin(arr2)

np.int64(0)

In [19]:
np.sum(arr2)

np.int64(54)

In [20]:
np.mean(arr2)

np.float64(6.0)

In [21]:
np.median(arr2)

np.float64(6.0)

In [22]:
np.std(arr2)

np.float64(2.581988897471611)

In [23]:
np.log(arr2)

array([[0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509]])

In [24]:
np.log10(arr2)

array([[0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 1.        ]])