In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1,100,10)
arr1

array([18, 92, 22, 99, 34, 12, 13, 95, 76, 31], dtype=int32)

In [3]:
arr2 = np.random.randint(30,100,(20,6))
arr2

array([[99, 40, 72, 53, 63, 44],
       [55, 54, 67, 52, 64, 86],
       [64, 35, 42, 68, 60, 44],
       [35, 39, 90, 61, 74, 42],
       [76, 92, 60, 46, 31, 47],
       [83, 65, 87, 94, 84, 95],
       [89, 69, 89, 60, 68, 43],
       [44, 33, 67, 69, 59, 36],
       [48, 47, 59, 33, 45, 91],
       [85, 69, 69, 36, 90, 92],
       [58, 40, 35, 65, 32, 74],
       [75, 64, 96, 61, 42, 76],
       [44, 72, 48, 48, 91, 50],
       [55, 89, 52, 52, 42, 67],
       [30, 79, 83, 80, 43, 81],
       [81, 43, 36, 60, 51, 79],
       [37, 47, 33, 65, 46, 46],
       [99, 78, 59, 74, 51, 44],
       [87, 32, 50, 32, 69, 70],
       [44, 40, 97, 60, 65, 68]], dtype=int32)

In [4]:
np.random.random(5)

array([0.79797527, 0.95487673, 0.28161809, 0.26701939, 0.3404336 ])

In [5]:
np.random.randn(10)

array([ 2.90234421,  0.99961814,  0.75558622, -1.22933374, -0.26966345,
        0.5596582 ,  0.80751762, -0.23116112, -0.1403046 ,  1.14628832])

#### 40 is used to split values of training and testing in data science

In [6]:
np.random.seed(40)  
arr1 = np.random.randint(1,100,10)
arr1

array([71, 92,  8, 38, 57, 51, 66, 13, 72, 20], dtype=int32)

In [7]:
np.random.permutation(arr1)

array([57,  8, 66, 51, 71, 92, 20, 72, 38, 13], dtype=int32)

In [8]:
np.random.rand(5)

array([0.84305835, 0.41027156, 0.28155881, 0.23409665, 0.40172498])